title: Junyu Zhang # name of the site
author: Junyu Zhang # name of site's author
email: junyu.zhang0088@outlook.com # email of site's author
url: https://junyuzhang567.github.io/ # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  <p> PhD </p>
  <p> Research fellow, Queen's Univeristy Belfast </p>
  <p> FRM part I exam passed, CFA III exam candidate.</p>
  <p> Email: junyu.zhang0088@outlook.com </p>
permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
